In [1]:
##imports
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import os
import sys
from matplotlib import pyplot as plt
sys.path.append(os.path.join(os.getcwd(), '..'))
from datetime import datetime, timedelta

import importlib
%matplotlib inline
from tqdm import tqdm
import studies
importlib.reload(studies)
from studies.dataset_initializer import initialize_datasets
from studies import DCLP3,DCLP5,ReplaceBG,Flair,Loop,PEDAP,IOBP2, T1DEXI, T1DEXIP
from src import drawing, cdf, tdd, logger, pandas_helper
from studies.studydataset import StudyDataset
import logging
logger = logger.Logger.get_logger("output_validation copy.ipynb",logging.INFO)

def save_figure(fig, name):
    notebook_path = os.path.join(os.getcwd(),'..','docs','assets')
    path = os.path.join(notebook_path, name+'.png')
    fig.savefig(path, bbox_inches='tight', dpi=300)

## Load Study Data

In [2]:
data_path = os.path.join(os.getcwd(), '..', 'data', 'raw')
initialized_datasets = list(initialize_datasets(data_path).values())

[18:15:47] Unmatched folders:
[18:15:47]   .gitkeep
[18:15:47]   skip
[18:15:47]   .DS_Store
[18:15:47] Successfully matched studies with folders:
[18:15:47]   IOBP2 : /Users/jan/git/nudgebg/babelbetes/notebooks/../data/raw/IOBP2 RCT Public Dataset.zip
[18:15:47]   Flair : /Users/jan/git/nudgebg/babelbetes/notebooks/../data/raw/FLAIRPublicDataSet.zip
[18:15:47]   PEDAP : /Users/jan/git/nudgebg/babelbetes/notebooks/../data/raw/PEDAP Public Dataset - Release 4 - 2025-04-10.zip
[18:15:47]   DCLP3 : /Users/jan/git/nudgebg/babelbetes/notebooks/../data/raw/DCLP3 Public Dataset - Release 3 - 2022-08-04.zip
[18:15:47]   DCLP5 : /Users/jan/git/nudgebg/babelbetes/notebooks/../data/raw/DCLP5_Dataset_2022-01-20-5e0f3b16-c890-4ace-9e3b-531f3687cf53.zip
[18:15:47]   ReplaceBG : /Users/jan/git/nudgebg/babelbetes/notebooks/../data/raw/REPLACE-BG Dataset-79f6bdc8-3c51-4736-a39f-c4c0f71d45e5
[18:15:47]   Loop : /Users/jan/git/nudgebg/babelbetes/notebooks/../data/raw/Loop study public dataset 2023-01-31
[18:15:47]   T1DEXI : /Users/jan/git/nudgebg/babelbetes/notebooks/../data/raw/T1DEXI - DATA FOR UPLOAD.zip
[18:15:47]   T1DEXIP : /Users/jan/git/nudgebg/babelbetes/notebooks/../data/raw/T1DEXIP - DATA FOR UPLOAD.zip

In [3]:
processed_studies = []

def current_time():
  return datetime.now().strftime("%H:%M:%S")

with tqdm(total=len(initialized_datasets)*4, desc=f"", bar_format='Step {n_fmt}/{total_fmt}: {desc} |{bar}', unit="step", leave=False) as progress:
  for study in initialized_datasets:
      tqdm.write(f"[{current_time()}] Starting {study.study_name} ...")
      #check if file exists
      if not os.path.exists(study.study_path):
        #tqdm.write(f"[{current_time()}] File {study.study_path} not found. Skipping...")
        logger.warning(f"Skipping {study.study_name} as file {study.study_path} not found")
        progress.update(4)
      else:
        try:
          start = datetime.now()
          progress.set_description_str(f"{study.study_name}: Loading data...")
          study.load_data(subset=False)
          progress.update(1)

          progress.set_description_str(f"{study.study_name}: Extracting CGM...")
          study.extract_cgm_history(); 
          progress.update(1)
      
          progress.set_description_str(f"{study.study_name}: Extracting bolus...")
          study.extract_bolus_event_history(); 
          progress.update(1)

          progress.set_description_str(f"{study.study_name}: Extracting Basal...")
          study.extract_basal_event_history(); 
          progress.update(1)
          tqdm.write(f"[{current_time()}] Finished {study.study_name} took {(datetime.now()-start).total_seconds():.1f} seconds")
          processed_studies.append(study)
        except Exception as e:
          logger.error(f"Error processing {study.study_name}: {e}")
        
logger.info(f"Finished processing {len(processed_studies)} studies")
logger.info(f"Processed studies: {[study.study_name for study in processed_studies]}")

Step 0/36: IOBP2: Loading data... |

[18:15:49] Starting IOBP2 ...

Step 4/36: Flair: Loading data... |█

[18:16:13] Finished IOBP2 took 24.4 seconds
[18:16:13] Starting Flair ...

Step 8/36: PEDAP: Loading data... |██▏

[18:17:12] Finished Flair took 58.7 seconds
[18:17:12] Starting PEDAP ...

Step 11/36: PEDAP: Extracting Basal... |███

26562
26562
26519
26519
26804
26804
24989
24989
23121
23121
15304
15304
43477
43477
40582
40582
37269
37269
26245
26245
3603
3603
46864
46864
18986
18986
14960
14960
37628
37628
18917
18917
36106
36106
35355
35355
49227
49227
27628
27628
36436
36436
44241
44241
11218
11218
33654
33654
42190
42190
38997
38997
28562
28562
35342
35342
37828
37828
12755
12755
11824
11824
10620
10620
10908
10908
47575
47575
32720
32720
35279
35279
22246
22246
19166
19166
14737
14737
19092
19092
18952
18952
22985
22985
31438
31438
30321
30321
15763
15763
31740
31740
34271
34271
23993
23993
26886
26886
14279
14279
37659
37659
9178
9178
39637
39637
22445
22445
34699
34699
37358
37358
31786
31786
13638
13638
36679
36679
25638
25638
47186
47186
9586
9586
26734
26734
31434
31434
32820
32820
1930
1930
30238
30238
11864
11864
95
95
35358
35358
25571
25571
23338
23338
21137
21137
37950
37950
39465
39465
42052
42052
1879
1879
24981
24981
40557
40557
34649
34649
6979
6979
38225
38225
20502
20502
33864
33864
19815
19815
38863
38863
21466
21466
30062
30062
28249
28249
25765
25765
13315
13315
21159
21159
44596
44596
17292
17292
13260
13260
32443
32443
24194
24194
1877
1877
38912
38912

Step 12/36: DCLP3: Loading data... |███▎

[18:18:11] Finished PEDAP took 59.3 seconds
[18:18:11] Starting DCLP3 ...

Step 16/36: DCLP5: Loading data... |████▍

[18:18:25] Finished DCLP3 took 14.3 seconds
[18:18:25] Starting DCLP5 ...

Step 20/36: ReplaceBG: Loading data... |█████▌

[18:18:48] Finished DCLP5 took 22.8 seconds
[18:18:48] Starting ReplaceBG ...

Step 24/36: Loop: Loading data... |██████▋            [18:19:16] loop_cgm.parquet already exists. Skipping conversion.
[18:19:16] loop_basal.parquet already exists. Skipping conversion.
Step 25/36: Loop: Extracting CGM... |██████▉

[18:19:16] Finished ReplaceBG took 27.9 seconds
[18:19:16] Starting Loop ...

Step 28/36: T1DEXI: Loading data... |███████▊

[18:21:16] Finished Loop took 120.3 seconds
[18:21:16] Starting T1DEXI ...

Step 32/36: T1DEXIP: Loading data... |████████▉

[18:21:54] Finished T1DEXI took 37.8 seconds
[18:21:54] Starting T1DEXIP ...

[18:22:02] Finished processing 9 studies
[18:22:02] Processed studies: ['IOBP2', 'Flair', 'PEDAP', 'DCLP3', 'DCLP5', 'ReplaceBG', 'Loop', 'T1DEXI', 'T1DEXIP']

[18:22:02] Finished T1DEXIP took 7.8 seconds

## Check for duplicates

In [4]:
def find_repetitive_values(df,date_col,value_col):
    b_repetitive = (df.sort_values(by=[date_col])[value_col].diff() == 0) & \
                   (df.sort_values(by=[date_col])[date_col].diff() < timedelta(hours=12))
    return b_repetitive

results = {}
for study in tqdm(processed_studies):
    print(study.study_name)
    n_bolus_duplicates = study.bolus_event_history.duplicated(subset=['patient_id', 'datetime', 'delivery_duration']).sum()
    n_basal_duplicates = study.basal_event_history.duplicated(subset=['patient_id','datetime']).sum()
    n_cgm_duplicates = study.cgm_history.duplicated(subset=['patient_id','datetime']).sum()
    n_basal_repetitive = study.basal_event_history.groupby('patient_id').apply(lambda x: find_repetitive_values(x, 'datetime', 'basal_rate'),include_groups=False).sum()
    results[study.study_name] = {'n_bolus_duplicates': n_bolus_duplicates,
                                'n_basal_duplicates': n_basal_duplicates,
                                'n_cgm_duplicates': n_cgm_duplicates,
                                'n_basal_repetitive': n_basal_repetitive}
results = pd.DataFrame(results).T
results

  0%|          | 0/9 [00:00<?, ?it/s]

IOBP2

 11%|█         | 1/9 [00:03<00:29,  3.65s/it]

Flair

 22%|██▏       | 2/9 [00:04<00:15,  2.19s/it]

PEDAP

 33%|███▎      | 3/9 [00:06<00:11,  2.00s/it]

DCLP3

 44%|████▍     | 4/9 [00:07<00:08,  1.74s/it]

DCLP5

 56%|█████▌    | 5/9 [00:09<00:06,  1.70s/it]

ReplaceBG

 67%|██████▋   | 6/9 [00:11<00:05,  1.83s/it]

Loop

 78%|███████▊  | 7/9 [00:38<00:19,  9.92s/it]

T1DEXI

100%|██████████| 9/9 [00:39<00:00,  4.37s/it]

T1DEXIP

,n_bolus_duplicates,n_basal_duplicates,n_cgm_duplicates,n_basal_repetitive
IOBP2,0,0,0,2304446
Flair,0,0,0,44945
PEDAP,0,0,0,0
DCLP3,39,2,49,2603
DCLP5,33,0,5,90318
ReplaceBG,0,0,436,64986
Loop,54,0,2227265,10502324
T1DEXI,0,0,0,244751
T1DEXIP,0,0,0,29236

### Check for repetitive values

In [ ]:
import studies
import importlib
importlib.reload(studies)
pedap = initialized_datasets[2]
pedap.load_data(subset=False)
pedap.extract_cgm_history()
pedap.extract_bolus_event_history()
pedap.extract_basal_event_history()

        patient_id  basal_rate            datetime
1341309        103       0.000 2020-06-09 14:27:45
1341320        103       0.205 2020-06-09 15:22:10
1341763        103       0.180 2020-06-09 17:01:57
1341767        103       0.000 2020-06-09 17:21:53
1341772        103       0.180 2020-06-09 17:36:50
...            ...         ...                 ...
7141018         28       1.627 2022-07-29 22:02:16
7141020         28       1.631 2022-07-29 22:12:14
7141021         28       0.350 2022-07-29 22:17:15
7141029         28       0.000 2022-07-29 22:57:10
7141034         28       0.350 2022-07-29 23:20:50

[6233913 rows x 3 columns]

In [ ]:
## Check for NaN values

In [ ]:
results = {}
for study in processed_studies:
    n_bolus = study.bolus_event_history.bolus.isna().sum()
    n_basal = study.basal_event_history.basal_rate.isna().sum()
    n_cgm = study.cgm_history.cgm.isna().sum()
    results[study.study_name] = {'n_bolus_nans': n_bolus,
                                'n_basal_nans': n_basal,
                                'n_cgm_nans': n_cgm}
results = pd.DataFrame(results).T
display(results)

## Visualize Distributions

In [ ]:
study_name_dict = {study.study_name: study for study in processed_studies}
colors = plt.cm.Set2(np.linspace(0, 1, len(study_name_dict)))

### Patients

In [ ]:
#visualize number of patient ids per study and data type as bar chart 
from src import cdf
f = plt.figure(figsize=(8,2)); ax = plt.gca()
num_patients = {study_name: len(study.cgm_history[StudyDataset.COL_NAME_PATIENT_ID].unique()) for study_name, study in study_name_dict.items()}
ax.bar(num_patients.keys(), num_patients.values(), color=colors)    
plt.title('Number of patients per study')
save_figure(f, 'num_patients_per_study')

### Data Points

In [ ]:
# Data points per study

import ipywidgets as widgets
from IPython.display import display

# Create a radio button for selecting normalization
normalize_radio = widgets.RadioButtons(
    options=[('No', False), ('Yes', True)],
    description='Normalize:',
    disabled=False
)

def plot_data_points(normalize):
    # Calculate the number of data points for CGM, bolus, and basal for each study
    num_data_points = {
        'Bolus': {study_name: len(study.bolus_event_history) for study_name, study in study_name_dict.items()},
        'Basal': {study_name: len(study.basal_event_history) for study_name, study in study_name_dict.items()},
        'CGM': {study_name: len(study.cgm_history) for study_name, study in study_name_dict.items()}
    }

    # Create a figure and axis
    fig, ax = plt.subplots(figsize=(8, 3))

    # Normalize the data points if required
    if normalize:
        total_data_points = {study_name: sum([num_data_points[datatype][study_name] for datatype in num_data_points]) for study_name in study_name_dict.keys()}
        num_data_points_normalized = {datatype: {study_name: (count / total_data_points[study_name]) * 100 for study_name, count in counts.items()} for datatype, counts in num_data_points.items()}
    else:
        num_data_points_normalized = num_data_points

    index = np.arange(len(study_name_dict))
    bar_width = 0.25
    # Plot the data points as bar charts
    bar1 = ax.bar(index, num_data_points_normalized['CGM'].values(), bar_width, label='CGM', color=drawing.colors['CGM'])
    bar2 = ax.bar(index + bar_width, num_data_points_normalized['Bolus'].values(), bar_width, label='Bolus', color=drawing.colors['Bolus'])
    bar3 = ax.bar(index + 2 * bar_width, num_data_points_normalized['Basal'].values(), bar_width, label='Basal', color=drawing.colors['Basal'])

    # Add labels, title, and legend
    ax.set_xlabel('Study')
    ax.set_ylabel('Percentage of Data Points' if normalize else 'Number of Data Points')
    ax.set_title(f"Data Point Numbers {'Normalized' if normalize else ''}")
    ax.set_xticks(index + bar_width)
    ax.set_xticklabels(study_name_dict.keys(), rotation=45)
    ax.legend()

    # Show the plot
    plt.tight_layout()
    plt.show()

# Display the radio button and plot
widgets.interact(plot_data_points, normalize=normalize_radio)
save_figure(f, 'data_points_per_study')

#### Patient Days

In [ ]:
#get all patient day counts into single dataframe
num_days_patient = {study_name: study.bolus_event_history.groupby(StudyDataset.COL_NAME_PATIENT_ID).apply(lambda x: x.datetime.dt.date.nunique(),include_groups=False)
                    for study_name, study in study_name_dict.items()}

num_days_patient = pd.DataFrame(num_days_patient).reset_index()
num_days_patient = num_days_patient.melt(id_vars=['patient_id'], value_vars=num_days_patient.columns, var_name='study', value_name='count')
num_days_patient = num_days_patient.dropna()

In [ ]:
#draw
f = plt.figure(figsize=(8,3)); ax = plt.gca()
num_days_patient.plot.box(ax=ax,by='study',column='count',showfliers=False)
plt.title('Patient days per study')
plt.tight_layout()
save_figure(f, 'numdays')

- PEDAP seems least controlled in terms of study duration
- DCLP should be more close to 90

In [ ]:
#get days and samples
plt.figure(figsize=(8,3)); ax = plt.gca()
temp = num_days_patient.groupby('study')['count'].agg(['sum'])
temp.sort_values('sum',ascending=True,inplace=True,)
temp.plot.bar(ax=ax)
plt.tight_layout()

## CDFs

### Boluses

In [ ]:
#CDF bolus
import logging
#del logger
f = plt.figure(figsize=(8,3)); ax = plt.gca()
#logger.level = logging.ERROR
for color, (study_name, study) in zip(colors, study_name_dict.items()):
    cdf.plot_cdf(study.bolus_event_history.bolus, ax=ax, color=color, linewidth=1)
ax.legend(study_name_dict.keys(),loc='upper right',bbox_to_anchor=(1.25, 1))
plt.title('CDF of Bolus Amount')
plt.xlim(0.01, 20)
plt.tight_layout()
ax.set_xscale('log');
save_figure(f, 'bolus_cdf');

Findings:
 - IOBP2 has 25% 0 bolus values

In [ ]:
#CDF bolus

f = plt.figure(figsize=(8,2)); ax = plt.gca()
for color, (study_name, study) in zip(colors, study_name_dict.items()):
    drawing.drawMovingAverage(ax,study.bolus_event_history.dropna(subset='bolus'),StudyDataset.COL_NAME_DATETIME,
                              StudyDataset.COL_NAME_BOLUS,color=color)
ax.legend(study_name_dict.keys(),loc='upper right',bbox_to_anchor=(1.25, 1))
plt.title('CDF of Bolus Amount')
save_figure(f, 'bolus_cdf')

#excluded bolues < 1 U
f = plt.figure(figsize=(8,2)); ax = plt.gca()
for color, (study_name, study) in zip(colors, study_name_dict.items()):
    temp = study.bolus_event_history
    temp = temp.loc[temp.bolus > 1]
    drawing.drawMovingAverage(ax,temp,StudyDataset.COL_NAME_DATETIME,
                              StudyDataset.COL_NAME_BOLUS,color=color)
ax.legend(study_name_dict.keys(),loc='upper right',bbox_to_anchor=(1.25, 1))
plt.title('CDF of Bolus Amount (>1U)')

save_figure(f, 'bolus_cdf_gt_1');

 - When reducing to boluses >1 unit, the micro boluses are avoided but in the pedap study, the patterns are also less pronounced.
 - Many more zero boluses in Flair (probably a result of suspension). Question is why this is so much more commin than in other pumps?

### Basal

In [ ]:
#CDF  Basal
from src import cdf
f = plt.figure(figsize=(8,3)); ax = plt.gca()
for color, (study_name, study) in zip(colors, study_name_dict.items()):
    cdf.plot_cdf(study.basal_event_history.basal_rate, ax=ax, color=color, linewidth=1)
ax.legend(study_name_dict.keys(),loc='upper right',bbox_to_anchor=(1.25, 1))
plt.title('CDF of Basal Rate')
plt.xlim(-.2, 3.5)
save_figure(f, 'basal_cdf')

In [ ]:
#daily basal rate

f = plt.figure(figsize=(8,3)); ax = plt.gca()
subset_studies = ['PEDAP']
for color, (study_name, study) in zip(colors, study_name_dict.items()):
    if study.basal_event_history.empty:
        logger.warning(f"{study_name} has no basal data")
        continue
    drawing.drawMovingAverage(ax,study.basal_event_history.dropna(subset='basal_rate'),StudyDataset.COL_NAME_DATETIME,
                              StudyDataset.COL_NAME_BASAL_RATE,color=color)
ax.legend(study_name_dict.keys(),loc='upper right',bbox_to_anchor=(1.25, 1))
plt.title('Daily Basal Rate')
plt.tight_layout()
save_figure(f, 'daily_basal')

We can clearly see which pumps modulate AID with basal and which don't. Those who do, show a clear daily pattern. Again, PEDAP is less pronounced in comparison.

### CGM

#### CDF

In [ ]:
#cgm cdf 
from src import cdf
f = plt.figure(figsize=(8,3)); ax = plt.gca()
for color, (study_name, study) in zip(colors, study_name_dict.items()):
    cdf.plot_cdf(study.cgm_history.cgm.sample(10000), ax=ax, color=color, linewidth=1,markersize=1)
ax.legend(study_name_dict.keys(),loc='upper right',bbox_to_anchor=(1.25, 1))
plt.xticks([0, 40, 70,180,250, 400])
plt.title('CGM Distribution')
plt.tight_layout()
save_figure(f, 'cgm_cdf');

In [ ]:
# display counts of cgms <40, >400
cgm_outliers = {}
for study_name, study in study_name_dict.items():
    cgm_outliers[study_name] = {'<40': (study.cgm_history.cgm < 40).sum(), '>400': (study.cgm_history.cgm > 400).sum()}
cgm_outliers_df = pd.DataFrame(cgm_outliers).T
display(cgm_outliers_df)

Findings:
- PEDAP has zero valued CGMs
- Loop, T1DEXI, T1DEXIP have values <40 and >400

In [ ]:
#daily CGM
from src import cdf
f = plt.figure(figsize=(8,3)); ax = plt.gca()
for color, (study_name, study) in zip(colors, study_name_dict.items()):
    drawing.drawMovingAverage(ax,study.cgm_history.sample(250000),StudyDataset.COL_NAME_DATETIME,
                              StudyDataset.COL_NAME_CGM,color=color)
ax.legend(study_name_dict.keys(),loc='upper right',bbox_to_anchor=(1.25, 1))
plt.tight_layout()
plt.title('Daily average CGM')
save_figure(f, 'dailycgm')

### TDDs

In [ ]:
#calculate Tdds for all studies
tdds_all_studies = {}

for study_name, study in tqdm(study_name_dict.items(), desc="Calculating TDDs for all studies"):
    tdd_bolus = study.bolus_event_history.groupby('patient_id').apply(lambda x: tdd.calculate_daily_bolus_dose(x), include_groups=False)
    tdd_basal = study.basal_event_history.groupby('patient_id').apply(lambda x: tdd.calculate_daily_basal_dose(x), include_groups=False)
    tdds = pd.concat([tdd_bolus, tdd_basal], axis=1)
    tdds_all_studies[study_name] = tdds

In [ ]:
#calcualte patient and study means
temp = [tdds.reset_index().assign(study=study) for study,tdds in tdds_all_studies.items()]
temp = pd.concat(temp)
patient_means = temp.dropna().groupby(['study','patient_id'])[['bolus','basal']].median()#means by patient
display(patient_means.sample(5))

#study means
study_means = patient_means.groupby('study').median()#mean per study
study_means['sum'] = study_means.bolus+study_means.basal
display(study_means)

In [ ]:
#display as stacked bar chart 
plt.figure(figsize=(8,4)); ax=plt.gca()
study_means = study_means.sort_values(by='sum')
study_means[['bolus','basal']].plot.bar(stacked=True,ax=ax)
plt.tight_layout()
save_figure(plt.gcf(), 'output_validation_study_tdds')

In [ ]:
# Assign color values based on study column
study_colors = {study: color for study, color in zip(study_name_dict.keys(), colors)}
temp = patient_means.reset_index(level=0)
plt.figure(figsize=(6,6)); ax=plt.gca()
for study, df in temp.groupby('study'):
    ax.scatter(df.bolus, df.basal,c=study_colors[study],alpha=0.5,label=study)
plt.legend()
ax.set_xlabel('bolus');ax.set_ylabel('basal')
save_figure(plt.gcf(), 'output_validation_patient_tdds')

## Data overlaps

In [ ]:
%matplotlib widget
import ipywidgets as widgets
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import importlib
importlib.reload(drawing)

# Create figure and axis
f = plt.figure(figsize=(8, 17))
ax = f.gca()

# Widgets
study_name_dict = {study.study_name: study for study in processed_studies}
study_widget = widgets.Dropdown(options=study_name_dict.keys(), description='Study:')
datatype_widget = widgets.Dropdown(options=['Bolus', 'Basal', 'CGM', 'All'], description='Data:')
relative_dates_widget = widgets.Checkbox(value=True, description='Relative Dates')
save_widget = widgets.Checkbox(value=False, description='Save')

widget_box = widgets.HBox([study_widget, datatype_widget, relative_dates_widget, save_widget])



def get_patient_min_dates(dfs, datetime_col='datetime'):
    combined = pd.concat([
        df[[datetime_col, 'patient_id']] for df in dfs if df is not None and not df.empty
    ])
    return combined.groupby('patient_id')[datetime_col].min()


def normalize_df(df, patient_min_dates, datetime_col='datetime', relative=True):
    df = df.copy()
    if relative:
        df['day_since_start'] = df[datetime_col] - df['patient_id'].map(patient_min_dates)
        df['x'] = df['day_since_start'].dt.days
    else:
        df['x'] = df[datetime_col].dt.date
    return df

def draw_data_overlap(study_name, datatype, relative_dates, save, ax, f, slider):
    study = study_name_dict[study_name]
    ax.cla()

    # Extract relevant dataframes
    data_sources = {}
    if datatype in ['CGM', 'All']:
        data_sources['CGM'] = study.extract_cgm_history()
    if datatype in ['Bolus', 'All']:
        data_sources['Bolus'] = study.extract_bolus_event_history()
    if datatype in ['Basal', 'All']:
        data_sources['Basal'] = study.extract_basal_event_history()

    ## Calculate min datetimes only for selected data
    patient_min_dates = get_patient_min_dates(data_sources.values())
    offsets = {'CGM': 0.2,'Bolus': -0.2,'Basal': 0}
    
    # Normalize and plot
    for key, df in data_sources.items():
        offset = offsets[key]
        temp = normalize_df(df, patient_min_dates, relative=relative_dates)
        temp['patient_id'] = temp['patient_id'].astype('float')
        #temp = temp.groupby(['patient_id']).x.unique().reset_index().explode('x')
        #ax.scatter(temp.x, temp.patient_id.astype('float')+offset, color=drawing.colors[key], s=1, alpha=.5)
        drawing.draw_presence_matrix(ax, temp, 'x', 'patient_id', offset=offset, color=drawing.colors[key], alpha=.5)
         

    # Axes setup
    if relative_dates:
        ax.set_xlabel("Days since first data point")
        # xticks = np.arange(ax.get_xlim()[0], ax.get_xlim()[1], 14)
        # ax.set_xticks(xticks)
    else:
        ax.set_xlabel("Date")
    
    ax.set_ylabel("Patient ID")
    ax.tick_params(axis='x', labelsize='x-small', rotation=90)
    ax.tick_params(axis='y', labelsize='x-small')
    plt.tight_layout()
    plt.suptitle('')
    plt.title(f"{datatype.capitalize()} availability in {study_name}")
    
    if save:
        save_figure(f, f'presence_matrix_{study_name}_{datatype}')


# Interactive output
out = widgets.interactive_output(draw_data_overlap, {
    'study_name': study_widget,
    'datatype': datatype_widget,
    'relative_dates': relative_dates_widget,
    'save': save_widget,
    'ax': widgets.fixed(ax),
    'f': widgets.fixed(f),
    'slider': slider
})

display(widget_box, out)

## Data Amounts

In [ ]:
from functools import reduce

importlib.reload(pandas_helper)
results = {}
with tqdm(total=len(initialized_datasets), desc="Processing studies", unit="study") as progress:
    for study in initialized_datasets:
        basal = study.extract_basal_event_history()
        bolus = study.extract_bolus_event_history()
        cgm = study.extract_cgm_history()

        #get daily event counts
        cgm_counts = cgm.groupby(['patient_id',cgm.datetime.dt.date]).size()
        bolus_counts = bolus.groupby(['patient_id',bolus.datetime.dt.date]).size()
        basal_counts = basal.groupby(['patient_id',basal.datetime.dt.date]).size()

        combined_counts = pd.concat([cgm_counts, bolus_counts, basal_counts], axis=1, join='inner', keys=['CGM', 'Bolus', 'Basal'])
        combined_counts = combined_counts.reset_index()

        num_patients = combined_counts.patient_id.nunique()
        results[study.study_name] = {'num_patients': num_patients, 
                                     'num_days': len(combined_counts),
                                     'basal_days': len(basal_counts),
                                     'bolus_days': len(bolus_counts),
                                     'cgm_days': len(cgm_counts)}
        progress.update(1)

In [ ]:
df_results = pd.DataFrame(results).T.reset_index().rename(columns={'index': 'study'})
plt.figure(figsize=(8, 3)); ax = plt.gca()
temp = df_results.sum()[['num_days', 'basal_days', 'bolus_days', 'cgm_days']].rename({'num_days': 'Total', 'basal_days': 'Basal', 'bolus_days': 'Bolus', 'cgm_days': 'CGM'})
temp=temp.sort_values(ascending=False)
types = temp.index
temp.plot.bar(color=[drawing.colors[type] if type != 'Total' else 'green' for type in types],ax=ax)
plt.xticks(rotation=45,fontsize='x-small');
plt.title('Number of days with data')
plt.tight_layout()

In [ ]:
#draw results as filled area plot

plt.figure(figsize=(8, 5));ax = plt.gca()
for row in df_results.itertuples():
    avg_days = row.num_days/row.num_patients
    plt.fill_between([0, row.num_patients], [avg_days, avg_days], alpha=0.2, label=f"{row.study} ({row.num_patients:.0f}x{avg_days:.1f}={avg_days*row.num_patients:.0f})", edgecolor='black')
    plt.text(row.num_patients, avg_days, row.study, fontsize='small', ha='left', va='bottom', color='black', bbox=dict(facecolor='white', edgecolor='none', alpha=0.7))
plt.xlabel('number of subjects',fontsize='small')
plt.ylabel('number of days',fontsize='small')
plt.title('Days worth of data per study',fontsize='small')
plt.legend(loc='upper right', bbox_to_anchor=(.9, .9),fontsize='small')
plt.tight_layout()
#plt.ylim(-10,900);plt.xlim(-10,320)
save_figure(plt.gcf(), 'data_days_per_study')

In [ ]:
#stacked bar chart
temp = df_results.set_index('study')
temp = temp[['basal_days','bolus_days','cgm_days','num_days']]
#temp = temp.sort_values(by='num_days')
temp.plot.bar(stacked=False, figsize=(8, 4), color=[drawing.colors['Basal'], drawing.colors['Bolus'], drawing.colors['CGM'], 'green'])
plt.tight_layout()
plt.yscale('log')